title: Jenya Yelyashkevich
email: me@jenyay.com
description: ""
baseurl: "" 
url: "https://jenyay.com"

# Disable using the latest Minima release
#theme: minima
# And instead pull straight from GitHub via jekyll remote theme
remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme


# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: auto
  social_links:
    - { platform: rss,            user_url: "https://blog.jenyay.com/" }
    - { platform: github,         user_url: "https://github.com/jenyayel" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/profile/view?id=ADEAAADeW6sBW4Oz_qQmXiOwGu38dnTj4AXpD6g" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/2307459/jenya-y" }
    - { platform: instagram,      user_url: "https://www.instagram.com/jenyayel" }
